on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.5.0']
        os: [ubuntu-latest, windows-latest]
    
    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1.6.0
        with:
          version: ${{ matrix.julia-version }}
      - name: "Build package"
        uses: julia-actions/julia-buildpkg@v1
      - name: "Update package server"
        run: julia --color=yes --project=. -e 'ENV["JULIA_PKG_SERVER"] = ""; import Pkg; Pkg.update()'
        shell: bash
      - name: "Run tests"
        run: ./test_with_coverage.sh
        shell: bash
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
